### ISSUE TITLE
Item Drops in Void Fields Blocked

### ISSUE THREAD

**Issue by GHDevelop** [ThinkInvis/RoR2-TILER2#17]
With the mod installed, cells in Void Fields will not drop items when completed. Happens both in single-player and multiplayer. A number of other mods were used, however removing Tiler2 specifically fixed the bug.
[LogOutput.log](https://github.com/ThinkInvis/RoR2-TILER2/files/6262325/LogOutput.log)

**Comment by ThinkInvis** [comment]
It's an issue with R2API: https://github.com/ThinkInvis/RoR2-ClassicItems/issues/80#issuecomment-814224521

**Comment by ThinkInvis** [comment]
Appears to have been fixed by R2API 3.0.11.
