### ISSUE TITLE
Mismatch network Timeout Issue after R2API update

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [ThinkInvis/RoR2-TILER2#21]
Reports:
https://discord.com/channels/562704639141740588/562711077453037589/852744830533632081

There were other few, but this happened after the R2API update dropped.

**Comment by cheeeeeeeeeen** [comment]
![image](https://user-images.githubusercontent.com/26833961/121782514-525cf700-cbdc-11eb-9288-e665b1a40ee5.png)
Playing multiplayer; it's not possible to play with this one coming out.

**Comment by ThinkInvis** [comment]
Console logs related to the issue don't reveal much; my best guess is that it was due to a newly-created incompatibility between the StatHooks module and R2API.RecalculateStatsAPI. The former was just removed in TILER2 5.0.0, and I can't get this bug to happen with a dedicated server.

**Comment by cheeeeeeeeeen** [comment]
We will test this later. Yeah, my guess was also those since *literally that was the only change*.

**Comment by cheeeeeeeeeen** [comment]
Reoccurring issue, but not yet confirmed.

https://discord.com/channels/562704639141740588/562711077453037589/853976215823450142

**Comment by ThinkInvis** [comment]
Turns out this is very likely an R2API issue; InstantiateClone seems to be creating machine-dependent hashes.

**Comment by ThinkInvis** [comment]
Should be fixed in R2API v3.0.44.
