### ISSUE TITLE
Document breaking changes

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [ThinkInvis/RoR2-TILER2#26]
### Is your feature request related to a problem? Please describe.
It's been a while since I have modded, and I am not active in the scene anymore. However, I'd still love to maintain my existing mods. (Should also be applicable to ClassicItems, as mine depends on yours as an extension)

**Comment by ThinkInvis** [comment]
The only major breaking change in 6.0.0 was to the NetConfig module, which nobody *should* have had reason to hook into despite it technically having some public API. If they were: it was almost completely rewritten (transitioned from UNetWeaver to R2API.NetworkingAPI, no more orchestrator object), so they're better off starting over.

The "V2" names on CatalogBoilerplate implementations, which have been mapped to the normal names and marked obsolete for a while now, were also removed.

**Comment by cheeeeeeeeeen** [comment]
Noted!
