### ISSUE TITLE
Language Tokens are not initialized properly in Seekers of the Storm patch

### ISSUE THREAD

**Issue by Phreelosu** [ThinkInvis/RoR2-TILER2#30]
### Describe the Bug
Any new content's Language tokens that are relying on TILER2 are not properly initialized, but the items, drones and artifacts still work
![image](https://github.com/user-attachments/assets/c11586d7-3cec-4b82-b2f1-8b24f7fc9866)

### To Reproduce
1. Get a content mod that relies on TILER2
2. Go into logbook and see

### Expected Behavior
initialized language tokens

### Console Log
[LogOutput.log](https://github.com/user-attachments/files/16824861/LogOutput.log)

### Additional Context
Found this small issue while helping Chen to update Gradius and Chill Drone to work with Gearbox's garbage DLC

**Comment by ThinkInvis** [comment]
Fixed by 23c519fcaed7eb67e7de2d690a6ee877a0fb159f, 95f1c5698ea651f9fc9355221b5d5d4cbb50defa, 5dd30053079b459d1fcdff06ecbe8be0959d0a4e, 9a5beebe739cae445726e124bb9d03865049f983.
